### ISSUE TITLE
feature request: show cf tags in different color

### ISSUE THREAD

**Issue by ArtskydJ** [atuttle/atom-language-cfml#17]
Right now, `<cf...>` tags and normal html tags show up as the same color.

Maybe have a setting where coldfusion tags are highlighted some other color?

**Comment by ArtskydJ** [comment]
Any chance of supporting this @atuttle?

**Comment by atuttle** [comment]
I think it's a great idea. Unfortunately i don't have the time or the motivation to learn the syntax for defining languages in atom (it's not my every day editor), so I can't add it. But pull requests are welcome. :)

**Comment by David-Polehonski** [comment]
@ArtskydJ 

Update: All cfml tags now have the class 'cfml' appened to them so you can define classes that target them in your own stylesheet now, see image below, it's not quite perfect yet but it's getting there.

![tag-highlighting](https://cloud.githubusercontent.com/assets/2487640/8550073/3e64d7e0-24c6-11e5-986b-a80916c8116f.PNG)

**Comment by ArtskydJ** [comment]
@David-Polehonski Sweet, I hope to try this out as soon as #35 is merged and released. Thanks for your work on this!

**Comment by atuttle** [comment]
published. please close this issue once you've verified the fix. :)

**Comment by ArtskydJ** [comment]
Using version `0.8.4`, adding the following to my `styles.less` file changes the cfml tags color:
```less
atom-text-editor::shadow {
	.tag.cfml {
		color: blue;
	}
}
```
Thanks!

**Comment by ArtskydJ** [comment]
In case anyone's interested, I like this highlighting better:
```less
atom-text-editor::shadow {
	.meta.tag.other.cfml, /* cffunction tags */
	.entity.name.tag.cfml,
	.punctuation.tag.cfml {
		color: #B80;
	}
}
```

**Comment by dajester2013** [comment]
Just FYI for those who have a special place in their heart for cfeclipse, you may want to check out atom-theme-cfeclipse.

**Comment by kliakos** [comment]
Any other ideas on cf tags color? Can't find anything really good.

**Comment by ArtskydJ** [comment]
@kliakos You mean the color of the tags? It depends on your theme, I suppose.

**Comment by atuttle** [comment]
Yep. I'm trying out [apathy](https://atom.io/themes/apathy-theme) today, and using 

```css
atom-text-editor::shadow {
    .meta.tag.other.cfml, /* cffunction < and > */
    .punctuation.tag.cfml, /* other < and > */
    .entity.name.tag.cfml { /* tag names */
      color: #AC58FA;
    }
}
```

**Comment by ArtskydJ** [comment]
I'm using
```less
atom-text-editor::shadow {
    .entity.name.tag.cfml {
        color: /* color here */;
    }
}
```
because otherwise the cffunction tags look funny.

And it more closely resembles how the html is highlighted in cfml files. (The html does not have `<` or `>` highlighted.)
